### ISSUE TITLE
Spae failed at checkpoint check_genomes_extract_output:

### ISSUE THREAD

**Issue by minhtrung1997** [linsalrob/spae#12]
I run
```
spae run --input /home/ktest/project/trungnguyen/DEV-85/data/CTU-05-22050001/fastq_dir/ --output  /home/ktest/project/trungnguyen/DEV-85/result/CTU-05-22050001/spae --temp-dir /scratch/ --threads 30
```
It erred at 58% at `checkpoint check_genomes_extract_output`

Log file
[230913_spae.log](https://github.com/linsalrob/spae/files/12596830/230913_spae.log)

Please check and help me!

**Comment by npbhavya** [comment]
Hi, 

Thanks for running spae and reporting the error. I am actively working on the code, so it still needs to be fixed. I have made a few updates. Can you try to run spae again? 

If you continue to run into an error, I suggest going into config.yaml file and updating the line from "subsample: "" " to " subsample: "--subsample" ". This would subsample the reads and try running assembly again. 

Let me know how this works out.
