### ISSUE TITLE
downsampling assemblies step

### ISSUE THREAD

**Issue by gbouras13** [linsalrob/spae#4]
Perhaps it may be worth implementing an option to downsample using a program like rasusa (or filtlong).

https://github.com/mbhall88/rasusa

I am finding that in some ONT sequenced phage isolates, those with lower coverage (15-100x) assemble fine with Flye, but those with very high coverage (500x plus) cause issues with Flye failing to assemble disjointigs. Recent preprint came to a similar conclusion for metaviromes.

https://www.biorxiv.org/content/10.1101/2023.02.12.527533v1.full.pdf

**Comment by gbouras13** [comment]
Downsampling to 10M bases with rasusa solves the issue with Flye (for my isolates) but not Unicycler (hifiasm).

**Comment by npbhavya** [comment]
This is fixed now, added this option to the config file. Change the --bases option in the conig file to 10M
